### ISSUE TITLE
Bug: [OnchainKitProvider] chain type incompatible

### ISSUE THREAD

**Issue by sergical** [coinbase/onchainkit#700]
### Describe the bug and the steps to reproduce it

1. Checkout https://github.com/sergical/ossummer/pull/17
2. Check `web/src/OnchainProviders.tsx`
3. See type error

Full TS error
```
Type '{ blockExplorers: { readonly default: { readonly name: "Basescan"; readonly url: "https://sepolia.basescan.org"; readonly apiUrl: "https://api-sepolia.basescan.org/api"; }; }; contracts: { ...; }; ... 10 more ...; readonly network: "base-sepolia"; } | { ...; }' is not assignable to type 'Chain'.
  Type '{ blockExplorers: { readonly default: { readonly name: "Basescan"; readonly url: "https://sepolia.basescan.org"; readonly apiUrl: "https://api-sepolia.basescan.org/api"; }; }; contracts: { ...; }; ... 10 more ...; readonly network: "base-sepolia"; }' is not assignable to type 'Chain'.
    Types of property 'fees' are incompatible.
      Type 'ChainFees<undefined> | undefined' is not assignable to type 'ChainFees<ChainFormatters | undefined> | undefined'.
        Type 'ChainFees<undefined>' is not assignable to type 'ChainFees<ChainFormatters | undefined>'.
          Types of property 'baseFeeMultiplier' are incompatible.
            Type 'number | ((args: ChainFeesFnParameters<undefined>) => number | Promise<number>) | undefined' is not assignable to type 'number | ((args: ChainFeesFnParameters<ChainFormatters | undefined>) => number | Promise<number>) | undefined'.
              Type '(args: ChainFeesFnParameters<undefined>) => number | Promise<number>' is not assignable to type 'number | ((args: ChainFeesFnParameters<ChainFormatters | undefined>) => number | Promise<number>) | undefined'.
                Type '(args: ChainFeesFnParameters<undefined>) => number | Promise<number>' is not assignable to type '(args: ChainFeesFnParameters<ChainFormatters | undefined>) => number | Promise<number>'.
                  Types of parameters 'args' and 'args' are incompatible.
                    Type 'ChainFeesFnParameters<ChainFormatters | undefined>' is not assignable to type 'ChainFeesFnParameters<undefined>'.
                      The types of 'block.transactions' are incompatible between these types.
                        Type '`0x${string}`[] | ({ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; ... 11 more ...; transactionIndex: number | null; } | { ...; } | { ...; } |...' is not assignable to type '`0x${string}`[] | ({ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; ... 11 more ...; transactionIndex: number | null; } | { ...; } | { ...; } |...'. Two different types with this name exist, but they are unrelated.
                          Type '({ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; typeHex: `0x${string}` | null; ... 10 more ...; transactionIndex: number | null; } | { ...; }...' is not assignable to type '`0x${string}`[] | ({ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; ... 11 more ...; transactionIndex: number | null; } | { ...; } | { ...; } |...'.
                            Type '({ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; typeHex: `0x${string}` | null; ... 10 more ...; transactionIndex: number | null; } | { ...; }...' is not assignable to type '`0x${string}`[]'.
                              Type '{ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; typeHex: `0x${string}` | null; ... 10 more ...; transactionIndex: number | null; } | { ...; } ...' is not assignable to type '`0x${string}`'.
                                Type '{ type: "legacy"; chainId?: number | undefined; yParity?: undefined; from: `0x${string}`; gas: bigint; hash: `0x${string}`; input: `0x${string}`; nonce: number; r: `0x${string}`; s: `0x${string}`; to: `0x${string}` | null; typeHex: `0x${string}` | null; ... 10 more ...; transactionIndex: number | null; }' is not assignable to type '`0x${string}`'.ts(2322)
types.d.ts(31, 5): The expected type comes from property 'chain' which is declared here on type 'IntrinsicAttributes & OnchainKitProviderReact'
```

Also issue with QueryClientProvider
<img width="997" alt="Screenshot 2024-06-24 at 10 50 25 PM" src="https://github.com/coinbase/onchainkit/assets/3760543/9f25a124-92aa-4151-97e6-fc02e3faaa1d">

This is when signed in and `Avatar` component is rendered (I think) - client stack trace below

```
Warning: Cannot update a component (`HotReload`) while rendering a different component (`Avatar`). To locate the bad setState() call inside `Avatar`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render at Avatar
QueryClientProvider.js:21 Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (QueryClientProvider.js:21:15)
    at useBaseQuery (useBaseQuery.js:28:91)
    at useQuery (useQuery.js:13:74)
    at useName (useName.js:26:73)
    at Avatar (Avatar.js:48:78)
```

### What's the expected behavior?

Render without errors

### What version of the libraries are you using?

"@coinbase/onchainkit": "0.22.3",
"viem": "2.x",
"wagmi": "^2.9.2",
"@privy-io/react-auth": "^1.71.0",
"@privy-io/server-auth": "^1.7.3",
"@privy-io/wagmi": "^0.2.10",

**Comment by kyhyco** [comment]
I pulled your PR locally and can't reproduce this error.

Try removing the entire `node_modules` folder and `yarn install` again.

I am using node 18.18.2 btw

<img width="1393" alt="Screenshot 2024-06-24 at 8 16 04 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/e456eeb8-ea91-4eb8-909c-62def7c0be80">

**Comment by sergical** [comment]
whaaaaaa :/ 

I tried that and I am getting this in my server stack too
```
 GET / 200 in 7ms
 ⨯ ../src/QueryClientProvider.tsx (18:11) @ useQueryClient
 ⨯ Internal error: Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (./node_modules/@coinbase/onchainkit/node_modules/@tanstack/react-query/build/modern/QueryClientProvider.js:19:15)
```

Added an Avatar component to the homepage https://github.com/sergical/ossummer/pull/17/commits/2d86dbb100bb17226b0aaaa7bdc7e673239165a6

Also are you not seeing the type error either in the OnchainProviders file?

**Comment by kyhyco** [comment]
What command are you running to get this?

Hmmm let me try checking the typescript. I am using neovim + biome. One sec

**Comment by sergical** [comment]
> neovim + biome
Wouldn't expect any less from you

**Comment by sergical** [comment]
> What command are you running to get this?
`yarn dev`

**Comment by kyhyco** [comment]
What do you get when you run `yarn check`?

This is what I get
```bash
./app/paymaster-bundler/_components/PaymasterBundlerDemo.tsx
32:22  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop

./src/OnchainProviders.tsx
25:11  Error: 'theme' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./src/components/layout/header/AccountConnect.tsx
38:30  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop

./src/components/layout/header/ProfileNavigation.tsx
45:22  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop
54:20  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop

./src/components/layout/header/ThemeToggle.tsx
28:36  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop
29:36  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop
30:36  Warning: JSX attribute values should not contain functions created in the same scope  react-perf/jsx-no-new-function-as-prop

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

**Comment by kyhyco** [comment]
Derp. I was on the main branch lol

One sec

**Comment by sergical** [comment]
LOL 

https://www.loom.com/share/299135368cfb4d8893ea4a176c4eb520

**Comment by kyhyco** [comment]
Yup I see it now

**Comment by kyhyco** [comment]
OK, I *think* this is a problem from OnchainKit bundling the viem and wagmi in the bundle directly.

Can you stay on for like 15 min? I can push a new release without those bundled in.

**Comment by sergical** [comment]
For you, I'll pull an all nighter

**Comment by sergical** [comment]
(kinda wanna make sure all of this works before buildathon deadline at the end of the month lol)

Thank you very much <3

**Comment by kyhyco** [comment]
on it

**Comment by kyhyco** [comment]
Aight 0.22.4 released. Think it's working now.

**Comment by sergical** [comment]
TS error went away. Still complaining about queryclientprovider :/

**Comment by kyhyco** [comment]
Where is that at? From `yarn dev`?

**Comment by sergical** [comment]
yeah, `yarn dev` and hit localhost:3000

**Comment by sergical** [comment]
latest on that branch has 0.22.4 and the Avatar component in HomePage.tsx. removing Avatar component doesn't render an error.

**Comment by kyhyco** [comment]
Yup see it

**Comment by kyhyco** [comment]
I think this is the same problem as we bundle up `@tanstack/react-query` as well

**Comment by sergical** [comment]
Forgot this isn't slack and i can't do `/giphy` but cool to know github is beta testing slash commands

<img width="357" alt="Screenshot 2024-06-25 at 12 39 41 AM" src="https://github.com/coinbase/onchainkit/assets/3760543/0f39e609-bfec-4ab9-b5f8-95c72a1045e5">

**Comment by kyhyco** [comment]
Verified this by removing `@tanstack/react-query` in the `package.json` and recompiling after using no cache.

**Comment by kyhyco** [comment]
Aight let me move that to peer dependencies as well

**Comment by sergical** [comment]
Not using graphql but wondering if that might cause an issue down the line too just inspecting the package.json for onchainkit

**Comment by kyhyco** [comment]
Hmm yes it might. We need to move away from getting eas attestations via graphql

**Comment by kyhyco** [comment]
v0.22.5 released

I'm gonna tackle the graphql stuff tomorrow. Clocked in 12+ hours already today lol

**Comment by sergical** [comment]
@Zizzamia this man is 🐐 just fyi
gn fren!

**Comment by sergical** [comment]
everything works as expected now

**Comment by cristobalbahe** [comment]
I think this problem is happening again with last versions of viem (2.21.55) and wagmi (2.14.1).
`
Type 'import("/Users/xxx/xxx/xxx/node_modules/@coinbase/onchainkit/node_modules/viem/_types/types/chain").Chain' is not assignable to type 'import("/Users/xxx/xxx/xxx/node_modules/viem/_types/types/chain").Chain'.
`

Also I am using the <FundButton /> which throws the following error:
`
WagmiProviderNotFoundError: useConfig must be used within WagmiProvider.
The above error occurred in the <FundButton> component. It was handled by the <ReactDevOverlay> error boundary. Error Component Stack
`
<img width="701" alt="Screenshot 2024-12-13 at 18 50 41" src="https://github.com/user-attachments/assets/a2ba238d-9cb6-4061-89e3-04b4330bdb69" />
